### ISSUE TITLE
Clarify the difference between rectangle and point addressing

### ISSUE THREAD

**Issue by belak** [kiibohd/kll#24]
As an example, I was using the following to experiment with setting a block of pixels, but it didn't seem to do anything:

```
A[exp] <= start, loops:1, pfunc:interp;
A[exp, 1] <= P[c:0%,r:0%](255, 0, 255), P[c:20%,r:20%](255, 0, 255);
```

CC @haata (Since it doesn't look like I can directly assign issues)

**Comment by haata** [comment]
Sorry this has taken so long.
But
[] brackets handle addressing, i.e. which pixel or where the pixel is located.
() represent the data manipulation on that pixel. So if a pixel has 3 channels, (255, 0, 255) would modify each of the 3 channels of the pixel with 255 on channel 1, 0 on channel 2 and 255 on channel 3. The usual mapping is channel 1 is Red, channel 2 is Green and channel 3 is Blue.
Now for single color leds, only channel 1 is used.
