### ISSUE TITLE
Cannot use Consumer Control "Mute", "ScanPreviousTrack", and "ScanNextTrack"

### ISSUE THREAD

**Issue by paradox460** [kiibohd/kll#29]
* **Firmware/Compiling Origin**:
https://github.com/paradox460/kll/blob/24e4a834e634b81085bcb67bb7d1a567b2bc4862/kll/layouts/infinity_ergodox/paradox_overlay_layer1.kll

* **KLL Snippet**:
```
U"D"         : CONS"SCANPREVIOUSTRACK";
U"F"         : CONS0x0CD;
U"G"         : CONS"ScanNextTrack";
```
* **OS**:

Mac OS X El Capitan 10.11.6, KLL compilation in Arch Linux Docker container from kiibohd/firmware project

* **Version**:
KLL v0.5c

* **Reproduction Steps**:
1. Add one of the aforementioned Consumer Control Codes (`CONS`) to your KLL file.
2. Attempt to compile for the Ergodox Infinity.
3. Compilation fails for SOME named CONS, but not for others.

   Confirmed working:
   + `Mute`
   + `VolumeDown`
   + `VolumeUp`
   + Hex/Decimal coded `CONS` (eg `CONS0x0CD` for `PausePlay`)

   Confirmed Not Working:
   + `ScanPreviousTrack`
   + `ScanNextTrack`
   + `PausePlay`

Additionally, attempting to use `CON` instead of `CONS` (as indicated by [this document](https://github.com/kiibohd/kll-spec/tree/0.5c)) results in complete failures.

* **Resulting Issue**:
Attempting to use _some_ consumer control codes results in failure of compilation. Hexadecimal/Decimal variants of said consumer control codes compile and work fine

**Comment by haata** [comment]
kll transitioned to using a separate database for HID names. The old scheme where spaces were removed automatically doesn't work anymore (there were some annoying conflicts). However, while preparing for the new configurator, I believe these symbolic names were added:
https://github.com/hid-io/layouts/blob/master/base/base.json#L1541
https://github.com/hid-io/layouts/blob/master/base/base.json#L1566

You'll need to make sure your kll compiler is up-to-date.
