### ISSUE TITLE
The extra ISO key

### ISSUE THREAD

**Issue by henkv** [kiibohd/kll#3]
![Swedish ISO Layouy](http://hack.org/mc/images/KB_Sweden.png)

I cant find away to send the key between left shift and z which is a major problem if you use a Swedish layout and want to program.

**Comment by haata** [comment]
ISO Slash?

https://github.com/kiibohd/kll/blob/master/kll_lib/hid_dict.py#L363

**Comment by henkv** [comment]
yes, thank you. my bad
