### ISSUE TITLE
KLL compiler generates an incorrect frame if list-of-pixels notation is used more than once

### ISSUE THREAD

**Issue by kluelogic** [kiibohd/kll#30]
* **Firmware/Compiling Origin**:
KLL compiler

* **KLL Snippet**:

**This KLL works:**
```
A[tatejima, 1] <= P[21,22,30,31](255);
```

`generatedPixelmap.c`:
```
const uint8_t tatejima_frame1[] = {
	PixelAddressType_Index, /*21*/21,0,0,0, PixelChange_Set, 255,
	PixelAddressType_Index, /*22*/22,0,0,0, PixelChange_Set, 255,
	PixelAddressType_Index, /*30*/30,0,0,0, PixelChange_Set, 255,
	PixelAddressType_Index, /*31*/31,0,0,0, PixelChange_Set, 255,
	PixelAddressType_End
};
```

**But this KLL doesn't work:**
```
A[tatejima, 1] <= P[21,22,30,31](255),P[7,14,20,29,38](0);
```

`generatedPixelmap.c`:
```
const uint8_t tatejima_frame1[] = {
	PixelAddressType_Index, /*21*/21,0,0,0, PixelChange_Set, 255,
	PixelAddressType_Index, /*7*/7,0,0,0, PixelChange_Set, 0,
	PixelAddressType_End
};
```

* **OS**:
Ubuntu 18.04.1 LTS bionic

* **Version**:
kll repo: commit 89bdc906f71c20a62203e938b0a9bcbd7d792903

* **Reproduction Steps**:
I used `ergodox.bash` to compile.

* **Resulting Issue**:
It seems KLL compiler takes only the first pixel of each list.

**Comment by haata** [comment]
Interesting.

Did a quick test, yep this is a bug. I'm suspecting either a parsing or datastructure issue as the emitter seems to be working correctly.

I'm going to add `A[tatejima, 1] <= P[21,22,30,31](255),P[7,14,20,29,38](0);` as part of the unit test which tries to regenerate a kll file after parsing.

It currently regenerates the following kll (incorrectly, hence the bug):
```
A[tatejima, 1] <= P[021](255), P[007](0); # A[tatejima, 1] <= P[21,22,30,31](255),P[7,14,20,29,38](0); # AF[tatejima, 1]
```

**Comment by haata** [comment]
This should be fixed now. Thanks for reporting this!

**Comment by kluelogic** [comment]
Confirmed it works. Thanks a lot for the quick fix!
