### ISSUE TITLE
dual role keys?

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [kiibohd/kll#4]
Apologies if this is covered somewhere, I can't find an example of it in any of the example klls or the spec document. 

How can one create a dual role key with kll? 

I would like to make backspace and space behave like shift when held, and ctrl and alt to send escape and enter respectively when tapped. I currently accomplish this on an Atreus with the "Modifier with Tap key" tmk feature, e.g. `ACTION_MODS_TAP_KEY(MOD_RCTL, KC_ENT)`

edit: I'm using an ergodox infinity, thanks for your help!

**Comment by haata** [comment]
Yep, this is a often requested feature. I'll be adding support for tapped: "released without any other keys pressed" as well as time scheduled events (i.e. street fighter macros).

I already have a KLL spec proposed to add this, I'm hoping to start implumentation during my bike trip in Nov.

**Comment by AnthonyDiGirolamo** [comment]
Very cool, thanks for all your work! I'll keep an eye out for that.

**Comment by haata** [comment]
Here's the current issue open for it: https://github.com/kiibohd/controller/issues/2
